name: lp_customer_onboarding
description: "A new Flutter project."
 
#flutter version : 3.24.3 
#Dart sdk version : 3.5.3
#jdk version : 18.0.2.1

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  app_settings: ^5.1.1
  auto_route: ^7.4.0
  camera: ^0.11.0+2
  change_app_package_name: ^1.4.0
  dio: ^5.2.1+1
  dio_smart_retry: ^6.0.0
  duration: ^4.0.3
  flash: ^3.0.5+1
  cunning_document_scanner:
    git:
      url: https://github.com/romainboucher/cunning_document_scanner.git
      ref: 'feat/add-android-features'
  # ozsdk:
  #   git:
  #     url: https://gitlab.com/oz-forensics/oz-mobile-flutter-plugin.git
  #     ref: '8.14.0'
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_form_builder:   ^9.5.0
 # flutter_liveness_detection_randomized_plugin: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  form_builder_image_picker: ^4.1.0
  form_builder_validators:  ^11.0.0 
  gap: ^3.0.1
  geolocator: ^13.0.1
  hive_flutter: ^1.1.0
  hydrated_state_notifier: ^2.0.0
  hydrated_state_notifier_hive: ^2.0.0
  image_cropper: ^8.1.0
  image_picker: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  loading_animation_widget: ^1.3.0
  multiple_result: ^5.1.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  platform_info: ^4.0.0
  quickalert: ^1.1.0
  responsive_framework: ^1.1.0
  sentry_flutter: ^8.9.0
  shimmer: ^3.0.0
  slide_countdown: ^2.0.2
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.1.2
  velocity_x: ^4.1.0
  video_player: ^2.9.2
  video_compress: ^3.1.3
  lottie: ^3.2.0
  dotted_border: ^2.1.0
  #cunning_document_scanner: ^1.2.3
  #google_mlkit_document_scanner: ^0.3.0

  

dev_dependencies:
  auto_route_generator: ^7.1.1
  flutter_launcher_icons: "^0.14.1"
  flutter_gen_runner:
  build_runner: ^2.4.5
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.10
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0
  # launcher icon commands -:
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#FFFFFF"
flutter:
  
  
  generate: true
  uses-material-design: true
  
  assets:
     - assets/images/
     - assets/license.json
     - assets/animations/
      
  
  